# Generated by Clash Verge
mode: rule
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: false
log-level: info
ipv6: true
secret: ''
external-controller: 127.0.0.1:9097
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
global-client-fingerprint: chrome
tcp-concurrent: false
tun:
  enable: false
  stack: gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  device: Meta
  strict-route: false
  mtu: 9000
profile:
  store-selected: true
  store-fake-ip: true
geodata-mode: true
sniffer:
  enable: false
  sniff:
    TLS:
      ports:
        - 443
    HTTP:
      ports:
        - 80
      override-destination: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - +.lan
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - tls://8.8.4.4#DNS_Proxy
    - tls://1.0.0.1#DNS_Proxy
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
  nameserver-policy:
    geosite:cn,private:
      - 223.5.5.5
      - 114.114.114.114
      - https://dns.alidns.com/dns-query#h3=true
find-process-mode: strict
unified-delay: false
proxy-providers:
  qplunmokmf_provider:
    type: http
    path: ./qplunmokmf_provider.yaml
    url: ${domain}/${provider_url}/${TOKEN}
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: 手动切换
    type: select
    use:
      - qplunmokmf_provider
    proxies: null
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 36000
    tolerance: 50
    use:
      - qplunmokmf_provider
    proxies: null
  - name: 全球代理
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
  - name: 流媒体
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
  - name: DNS_Proxy
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
  - name: Telegram
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
  - name: Google
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
  - name: YouTube
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
  - name: Netflix
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
  - name: Spotify
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
      - DIRECT
  - name: HBO
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
  - name: Bing
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
  - name: OpenAI
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
  - name: Disney
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 流媒体
      - 手动切换
      - 自动选择
  - name: GitHub
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - 手动切换
      - 自动选择
      - DIRECT
  - name: 国内媒体
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - DIRECT
  - name: 本地直连
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - DIRECT
      - 手动切换
      - 自动选择
  - name: 漏网之鱼
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - DIRECT
      - 手动切换
      - 自动选择
  - name: AdGuard
    type: select
    use:
      - qplunmokmf_provider
    proxies:
      - REJECT
rule-providers:
  lan:
    type: http
    behavior: classical
    interval: 86400
    url: https://static.1024.do/fq/rules/Lan.txt
    path: ./Rules/lan.yaml
  reject:
    type: http
    behavior: domain
    url: https://static.1024.do/fq/rules/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://static.1024.do/fq/rules/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://static.1024.do/fq/rules/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://static.1024.do/fq/rules/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://static.1024.do/fq/rules/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://static.1024.do/fq/rules/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://static.1024.do/fq/rules/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://static.1024.do/fq/rules/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
  Disney:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/Disney.txt
    path: ./ruleset/disney.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/Netflix.txt
    path: ./ruleset/netflix.yaml
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/YouTube.txt
    path: ./ruleset/youtube.yaml
    interval: 86400
  HBO:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/HBO.txt
    path: ./ruleset/hbo.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/OpenAI.txt
    path: ./ruleset/openai.yaml
    interval: 86400
  Bing:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/Bing.txt
    path: ./ruleset/bing.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/Google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  GitHub:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/GitHub.txt
    path: ./ruleset/github.yaml
    ideepl.comnterval: 86400
  Spotify:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/Spotify.txt
    path: ./ruleset/spotify.yaml
    interval: 86400
  ChinaMaxDomain:
    type: http
    behavior: domain
    interval: 86400
    url: https://static.1024.do/fq/rules/ChinaMax_Domain.txt
    path: ./Rules/ChinaMaxDomain.yaml
  ChinaMaxIPNoIPv6:
    type: http
    behavior: ipcidr
    interval: 86400
    url: https://static.1024.do/fq/rules/ChinaMax_IP_No_IPv6.txt
    path: ./Rules/ChinaMaxIPNoIPv6.yaml
  AdGuardSDNSFilter:
    type: http
    behavior: classical
    url: https://static.1024.do/fq/rules/AdGuardSDNSFilter_Classical.txt
    path: ./ruleset/AdGuardSDNSFilter.yaml
    interval: 86400
  MyDirect:
    type: http
    behavior: domain
    interval: 86400
    url: ${domain}/${direct_url}
    path: ./Rules/MyDirect.yaml
  MyReject:
    type: http
    behavior: domain
    interval: 86400
    url: ${domain}/${reject_url}
    path: ./Rules/MyReject.yaml
  MyCustom:
    type: http
    behavior: classical
    url: ${domain}/${custom_url}
    path: ./Rules/MyCustom.yaml
    interval: 86400
rules:
  - RULE-SET,AdGuardSDNSFilter,AdGuard
  - RULE-SET,reject,AdGuard
  - RULE-SET,MyReject,AdGuard
  - RULE-SET,YouTube,YouTube,no-resolve
  - RULE-SET,Google,Google,no-resolve
  - RULE-SET,GitHub,GitHub
  - RULE-SET,telegramcidr,Telegram,no-resolve
  - RULE-SET,Spotify,Spotify,no-resolve
  - RULE-SET,Netflix,Netflix
  - RULE-SET,HBO,HBO
  - RULE-SET,Bing,Bing
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Disney,Disney
  - RULE-SET,proxy,全球代理
  - RULE-SET,gfw,全球代理
  - RULE-SET,applications,本地直连
  - RULE-SET,ChinaMaxDomain,本地直连
  - RULE-SET,ChinaMaxIPNoIPv6,本地直连,no-resolve
  - RULE-SET,lan,本地直连,no-resolve
  - RULE-SET,MyDirect,本地直连
  - RULE-SET,MyCustom,全球代理
  - GEOIP,CN,本地直连
  - MATCH,漏网之鱼
